### PR TITLE
fixed [#19] issue

### LINKED ISSUE #19: errors when deleting one of the modifiers
## Expected behavior
No errors when not all modifiers are activated.

## Actual behavior
getting erros because the js function is called, but the element the function refers to, is not being rendered.

## Steps to reproduce

  1. delet one modifier 
  2. press on the arrow or the dot navigation of the slider

### PR DESCRIPTION
**Pull request by christophsaile**
fixed #19 - bug

### CODE REVIEW

File: src/components/WcSlider/template.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export default (
         ${createStyle(styles)}
         <div class=${`slider ${data.modifier}`}>
             <div class="slider__wrapper-2col">
-                <div class="slider__main js_simple_dots simple">
+                <div class='slider__main'>
```
Comment (no-creative-name) [inline src/components/WcSlider/template.ts]: Please use double quotes for HTML attributes 🤓

File: src/components/WcSlider/WcSlider.ts [hunk 2]
```diff
@@ -11,106 +11,142 @@ class WcSlider extends Component<WcSliderProps, WcSliderState> {
...
-				); //because of dot_container.children array "-1"
+		}
+		//reset and set active to dot elements
+		if (e.type === 'after.lory.slide') {
+			for (
+				let i = 0, len = this.dot_container.children.length;
+				i < len;
+				i++
+			) {
+				this.dot_container.children[i].classList.remove('active');
```
Comment (no-creative-name) [inline src/components/WcSlider/WcSlider.ts]: This can be done in a cleaner way by using a .forEach loop:
`this.dot_container.children.forEach((child) => {
   child.classList.remove('active');
});`

File: src/components/WcSlider/WcSlider.ts [hunk 3]
```diff
@@ -11,106 +11,142 @@ class WcSlider extends Component<WcSliderProps, WcSliderState> {
...
+		}
+		//add click EventListener to each dot element
+		if (e.type === 'after.lory.init') {
+			for (let i = 0, len = this.dot_count; i < len; i++) {
+				this.dot_container.children[i].addEventListener('click', e => {
+					this.dotSliderLory.slideTo(
+						Array.prototype.indexOf.call(
+							this.dot_container.children,
+							e.target
+						)
```
Comment (no-creative-name) [inline src/components/WcSlider/WcSlider.ts]: You don't need the Array.prototype here:
`this.dot_container.children.indexOf(e.target)`

**Comment by christophsaile** [comment]
close #19
